[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"

[workspace]
members = [
    "pint", "primitives",
    "transaction", "block",
]
default-members = ["pint"]
exclude = []

[workspace.lints]
rust.unused_must_use = "deny"

[workspace.dependencies]
pint = { path = "pint" }
transaction = { path = "transaction" }
primitives = { path = "primitives" }
block = { path = "block" }
alloy-consensus = { version = "1.0.7", default-features = false }
