[package]
name = "pint"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
alloy-primitives = "1.2.0"
lock_api = "0.4.13"
rand = "0.9.1"
tokio-stream = "0.1.17"
tracing = "0.1.41"
